---
- name: "Install python2 and python-simplejson"
  become: True
  raw: "yum install -y python python-simplejson || (apt-get update && apt-get install -y python2.7 python-simplejson)"
  when: install_python==true

- name: Gather facts
  setup:

- name: Deploy hosts
  copy: src={{ item }} dest="/etc/{{ item }}"
  become: yes
  with_items:
    - hosts

- name: Deploy environment file
  template: src="environment.j2" dest="/etc/environment"
  become: yes
  register: hostname_change

- name: Set hostname file
  template: src="hostname.j2" dest="/etc/hostname"
  become: yes
  register: hostname_change

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {% for host in groups['all'] %}
        {{- hostvars[host]['ansible_default_ipv4']['address'] }} {{ hostvars[host]['inventory_hostname'] }}
        {% endfor %}
  become: yes

- name: Reboot machine
  shell: sleep 2 && /sbin/reboot
  become: yes
  async: 1
  poll: 0
  when: hostname_change.changed == true

- name: Wait for node come back
  wait_for: >
    host="{{ ansible_host }}"
    port=22
    delay=15
    timeout=60
  delegate_to: localhost
  when: hostname_change.changed == true
